### ISSUE TITLE
Add pace range to runs for each runner

### ISSUE THREAD

**Issue by daveshah** [daveshah/gatherto#30]
Looking at the bottom of the mock up [here](https://github.com/daveshah/gatherto/issues/7), you'll notice that when an athlete creates a run, that they can add their own pace range. No models exist for this so this issue would entail getting the basic building blocks setup for this and allowing for the run creator to add their own pace range to the run their creating / editing.

**Comment by matt-keibler** [comment]
@daveshah How would a runner describe the pace? Would it be in time per mile, time to complete the run, or something else?

**Comment by mbramson** [comment]
Time/mile. I'd assume Time/km should also be accommodated somehow? Mayhaps?

**Comment by matt-keibler** [comment]
Metric is are covered under #23 It got its own task since we want it to be tied to the user and we need to have the view display those values based on the user's preference.

**Comment by daveshah** [comment]
+1 for the time/mile. Most runners do this by min./mile and you'll typically see something like ```6:30/mi``` . As an example, here are the [Cleveland Marathon Race Results](http://results.xacte.com/?kw=riteaid). Note the pace column and it's format. Something like that should work, and we could always adjust when #23 is in place.

**Comment by daveshah** [comment]
FYI - updated the description. I should probably get in the habit of that!
