### ISSUE TITLE
Add location to Clubs

### ISSUE THREAD

**Issue by daveshah** [daveshah/gatherto#36]
Most clubs have a location (ex: Soletrain is in Rocky River / Lakewood). This should be an optional field on clubs.

**Comment by mbramson** [comment]
Should this just be a string field essentially? No fancy locationy things?

**Comment by mbramson** [comment]
So looking at https://github.com/daveshah/gatherto/pull/33, it looks like you're doing some fancy locationy things with Runs. That makes a lot of sense for Runs as the exact location that a run starts with matters. I'd argue that this is not the case for Clubs, as the Club location is more general. Does that make sense?

**Comment by daveshah** [comment]
@mbramson we're not doing any fancy things right now. Just determining exactly what the location model looks like. I'm not sure if a string type would be the right fit though. Some clubs could be by city / region - ex: http://orrrc.org/ is for the running community in and around Dayton and the Miami Valley. Others might have a "hub". What I mean by that is, a lot of clubs have strong running store ties. Soletrain for example http://www.soletrainrunners.com/ is strongly tied to Second Sole, so having Second Sole be the location of that club might make more sense. 
I think for a first go, this would just be a one-to-one relationship between club and location.

The reason we'll want to tie it to the location model is search with geolocation in mind.
