### ISSUE TITLE
Store the current user

### ISSUE THREAD

**Issue by mbramson** [daveshah/gatherto#43]
For clubs, when you create one, you are the de facto owner. For this to happen, we need to know which athlete is currently logged in.

One way to do this would be to put the athlete ID in session when they authenticate.

**Comment by daveshah** [comment]
@mbramson this should be handled by https://github.com/daveshah/gatherto/issues/14

**Comment by mbramson** [comment]
Ah, didn't see that.

**Comment by daveshah** [comment]
@mbramson no worries! On that note - there's a checkbox on that issue so we may want to break it up. Especially if you and @matt-keibler have any interest in any of those items. Lots to learn there!
