### ISSUE TITLE
Runs

### ISSUE THREAD

**Issue by daveshah** [daveshah/gatherto#7]
<img width="470" alt="screen shot 2016-07-31 at 6 57 23 am" src="https://cloud.githubusercontent.com/assets/949308/17276092/1c1c8116-56ec-11e6-9635-ba51d177081e.png">

Runs can be created by an athlete. Runs can have 1 or more runners (likewise an athlete will have 1 or more runs).  Runs have an optional title (though - this is required an a title like "Morning Run, Afternoon Run, or Evening Run" will be generated if one is not provided), location and a time. Runs have an optional pace range as well as an optional description. 

Runs have many comments.

**Comment by daveshah** [comment]
Not quite sure if phoenix.gen.model can handle many_to_many as this will be needed for runs.
May need to just roll a migration by hand: https://hexdocs.pm/ecto/Ecto.Migration.html

**Comment by daveshah** [comment]
@matt-keibler so, I wanted to talk through some of the above if you don't mind - just to bounce some ideas around...

Just from looking at the UI: 
- It kind of feels like "distance range" needs to be it's own thing. I think this would give us flexibility to swap out miles/km later on.

- It feels like location fits in here too so that we can be flexible with the model's info and reduce redundancy. 

- RSVP's get weird because we'll want a run to have runners and each runner seems like they'll have a "pace range" for this particular run.

Those were just my initial thoughts on this. What do you think? Does that seem off or like it's missing something and/or incorrect in any way?

**Comment by matt-keibler** [comment]
I agree with pretty much all of that. Do pace ranges vary from route to route? Should that be tied to the runner rather than the run?

For the UI, it would be nice to break the bottom portion into "runners in my pace range" and "all other runners". Also, should location have a beginning and end point? Are all runs closed loops?

**Comment by daveshah** [comment]
@matt-keibler 

> Do pace ranges vary from route to route  

I think they do in some cases. I'm training for a marathon right now so my pace varies depending on the day. Some days I have to run longer slower runs. Some days call for shorter faster runs. I think that having one tied to the runner though is a good idea since runners aren't training all the time and this could be the "default" pace (which could be overridden if desired maybe).

> For the UI, it would be nice to break the bottom portion into "runners in my pace range" and "all other runners"  

+1 to that! I like that idea a lot! 

> Also, should location have a beginning and end point? Are all runs closed loops?  

Most tend to start and end at the same location so I think just a starting point should work for now. I do know of some races that aren't like this but I think if we have demand for it, we could always add it.

**Comment by daveshah** [comment]
Going to scrap distance range and just add min/max and units to run model. Let's hardcode the units to miles for now.

**Comment by daveshah** [comment]
Depends on https://github.com/daveshah/gatherto/issues/29 and https://github.com/daveshah/gatherto/issues/30

**Comment by daveshah** [comment]
Removed myself as the only assignee on this since @matt-keibler is helping with this as well.
